### ISSUE TITLE
Simple EmojiPicker with String Binding

### ISSUE THREAD

**Issue by Jeehut** [danielsaidi/EmojiKit#1]
I read the articles in the docs, but I can't find a simple `EmojiPicker` kind of UI component that handles everything automatically and just provides me with a `Binding` parameter I need to pass a `String`. This is what I'm looking for, but this library seems to only provide the components to build such a UI, but not the UI itself. Or am I missing something?

**Comment by danielsaidi** [comment]
This is now added to the library. You can use the `EmojiGrid` to list emojis in a grid, and an `EmojiScrollGrid` to wrap the grid in a scroll view that automatically scrolls to the current selection.

**Comment by Jeehut** [comment]
Awesome! Thank you for letting me know. 👍
